### ISSUE TITLE
macos: symbol not found in flat namespace '_libiconv'

### ISSUE THREAD

**Issue by zevichen** [vnpy/vnpy_ctp#54]
咨询下我这个是什么问题：

- `Darwin mbp.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112 arm64`
- 使用的main分支代码
- python3.12，其实python3.10也是这个错误

整体操作步骤：

1. clone仓库
2. 创建.venv
3. 安装vnpy
4. pip install -e . 安装
5. 运行run.py报错

```log
/Users/xx/work/quant/vnpy_ctp/.venv/bin/python /Users/xx/work/quant/vnpy_ctp/script/run.py 
Traceback (most recent call last):
  File "/Users/xx/work/quant/vnpy_ctp/script/run.py", line 5, in <module>
    from vnpy_ctp import CtpGateway
  File "/Users/xx/work/quant/vnpy_ctp/vnpy_ctp/__init__.py", line 26, in <module>
    from .gateway import CtpGateway
  File "/Users/xx/work/quant/vnpy_ctp/vnpy_ctp/gateway/__init__.py", line 1, in <module>
    from .ctp_gateway import CtpGateway
  File "/Users/xx/work/quant/vnpy_ctp/vnpy_ctp/gateway/ctp_gateway.py", line 31, in <module>
    from ..api import (
  File "/Users/xx/work/quant/vnpy_ctp/vnpy_ctp/api/__init__.py", line 1, in <module>
    from .vnctpmd import MdApi
ImportError: dlopen(/Users/xx/work/quant/vnpy_ctp/vnpy_ctp/api/vnctpmd.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_libiconv'
```

**Comment by vnpy** [comment]
删除clone目录的dist/build/egg-info三个文件夹。

然后运行python setup.py build。

看看有没有报错？

**Comment by zevichen** [comment]
[zsh执行的命令日志](https://github.com/vnpy/vnpy_ctp/files/15077802/10.log)

依旧还是上面的错误。

**Comment by zevichen** [comment]
解决方法：`~/.zshrc`中添加动态库地址。

export DYLD_LIBRARY_PATH=/opt/homebrew/opt/libiconv/lib:/opt/homebrew/anaconda3/lib:$DYLD_LIBRARY_PATH

**Comment by vnpy** [comment]
感谢反馈
