### ISSUE TITLE
Mac 报错libiconv

### ISSUE THREAD

**Issue by stevenzhengzx** [vnpy/vnpy_ctp#55]
Traceback (most recent call last):
  File "/Users/zixun/Library/CloudStorage/OneDrive-个人/Python/github_projects/vnpy/run.py", line 4, in <module>
    from vnpy_ctp import CtpGateway
  File "/Users/zixun/Library/CloudStorage/OneDrive-个人/Python/github_projects/vnpy/vnpy_ctp/vnpy_ctp/__init__.py", line 26, in <module>
    from .gateway import CtpGateway
  File "/Users/zixun/Library/CloudStorage/OneDrive-个人/Python/github_projects/vnpy/vnpy_ctp/vnpy_ctp/gateway/__init__.py", line 1, in <module>
    from .ctp_gateway import CtpGateway
  File "/Users/zixun/Library/CloudStorage/OneDrive-个人/Python/github_projects/vnpy/vnpy_ctp/vnpy_ctp/gateway/ctp_gateway.py", line 31, in <module>
    from ..api import (
  File "/Users/zixun/Library/CloudStorage/OneDrive-个人/Python/github_projects/vnpy/vnpy_ctp/vnpy_ctp/api/__init__.py", line 1, in <module>
    from .vnctpmd import MdApi
ImportError: dlopen(/Users/zixun/Library/CloudStorage/OneDrive-个人/Python/github_projects/vnpy/vnpy_ctp/vnpy_ctp/api/vnctpmd.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_libiconv'

**Comment by dameassz** [comment]
请问解决了吗，我也碰到了

**Comment by stevenzhengzx** [comment]
没有。在github和官方论坛都提了，没有后续。

**Comment by vnpy** [comment]
请确保使用python.org下载的官方Python，不要使用【Anaconda】生态下的任何工具！！！包括（conda、miniconda、anaconda）
