### ISSUE TITLE
mac arm平台打开库文件报错

### ISSUE THREAD

**Issue by yilin-hust** [vnpy/vnpy_ctp#63]
/opt/anaconda3/envs/trade/bin/python /Users/frank/PycharmProjects/ctp/vnpy_ctp/script/run.py 
Traceback (most recent call last):
  File "/Users/frank/PycharmProjects/ctp/vnpy_ctp/script/run.py", line 5, in <module>
    from vnpy_ctp import CtpGateway
  File "/Users/frank/PycharmProjects/ctp/vnpy_ctp/vnpy_ctp/__init__.py", line 26, in <module>
    from .gateway import CtpGateway
  File "/Users/frank/PycharmProjects/ctp/vnpy_ctp/vnpy_ctp/gateway/__init__.py", line 1, in <module>
    from .ctp_gateway import CtpGateway
  File "/Users/frank/PycharmProjects/ctp/vnpy_ctp/vnpy_ctp/gateway/ctp_gateway.py", line 31, in <module>
    from ..api import (
  File "/Users/frank/PycharmProjects/ctp/vnpy_ctp/vnpy_ctp/api/__init__.py", line 1, in <module>
    from .vnctpmd import MdApi
ImportError: dlopen(/Users/frank/PycharmProjects/ctp/vnpy_ctp/vnpy_ctp/api/vnctpmd.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_libiconv'

**Comment by yilin-hust** [comment]
mac Intel平台下是正常的

**Comment by vnpy** [comment]
请参考这里的安装说明

**Comment by yilin-hust** [comment]
问题已解决，必须使用Python原生的3.10版本编译
